# Generated by Django 5.1 on 2024-09-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='email@ymail.com', max_length=254)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
