# Generated by Django 5.1 on 2024-09-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_students_class_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='class_attended',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
