# Generated by Django 5.1 on 2024-09-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_students_class_attended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='class_attended',
            new_name='class_attendance',
        ),
        migrations.AddField(
            model_name='students',
            name='average_score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
