# Generated by Django 5.1 on 2024-09-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_class_attended_students_class_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='quiz_submited',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
