# Generated by Django 5.1 on 2024-09-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_students_class_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='class_attendance',
            new_name='Attendance',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='cohort',
            new_name='Cohort',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='quiz_submited',
            new_name='Quiz_Submitted',
        ),
    ]
