# Generated by Django 5.1 on 2024-09-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_class_attendance_students_attendance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Quiz_Submitted',
            new_name='quiz_submited',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Email',
        ),
        migrations.AddField(
            model_name='students',
            name='mail',
            field=models.EmailField(default='email@ymail.com', max_length=254),
        ),
    ]
