# Generated by Django 5.1 on 2024-09-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_quiz_submitted_students_quiz_submited_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Attendance',
            new_name='class_attendance',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Cohort',
            new_name='cohort',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Name',
            new_name='name',
        ),
    ]
